---
version: "3.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/sonarr/config:/config
      - /data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped
# better comment
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/radarr/config:/config
      - /data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/lidarr/config:/config
      - /data:/data

    ports:
      - "8686:8686"
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/readarr/config:/config
      - /data:/data
    ports:
      - "8787:8787"
    restart: unless-stopped

  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
    volumes:
      - /nfs/mylar3/config:/config
      - /data:/data
    ports:
      - "8090:8090"
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1002
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /nfs/plex/config:/config
      - /data/media:/data/media
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/London
    volumes:
      - /nfs/tautulli/config:/config
    ports:
      - "8181:8181"
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
      - WEBUI_PORT=8080
    volumes:
      - /nfs/qbittorrent/config:/config
      - /data/torrents:/data/torrents
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/sabnzbd/config:/config
      - /data/usenet:/data/usenet
    ports:
      - "8081:8080"
    restart: unless-stopped
