---
version: "3.1"
services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/sonarr/config:/config
      - /data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/radarr/config:/config
      - /data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/lidarr/config:/config
      - /data:/data
    ports:
      - "8686:8686"
    restart: unless-stopped

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/readarr/config:/config
      - /data:/data
    ports:
      - "8787:8787"
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/prowlarr/config:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1002
      - VERSION=docker
      - PLEX_CLAIM=
    volumes:
      - /nfs/plex/config:/config
      - /data/media:/data/media
    restart: unless-stopped

  tautulli:
    image: linuxserver/tautulli:latest
    container_name: tautulli
    depends_on:
      - plex
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/London
    volumes:
      - /nfs/tautulli/config:/config
    ports:
      - "8181:8181"
    restart: unless-stopped

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
      - WEBUI_PORT=8080
    network_mode: "service:gluetun"
    volumes:
      - /nfs/qbittorrent/config:/config
      - /data/torrents:/data/torrents
    ports:
     # - "8080:8080"
     # - "6881:6881"
     # - "6881:6881/udp"
    restart: unless-stopped

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/sabnzbd/config:/config
      - /data/usenet:/data/usenet
    ports:
      - "8081:8080"
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - /nfs/bazarr/config:/config
      - /data:/data
    ports:
      - "6767:6767"
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600

  gluetun:
    container_name: gluetun
    environment:
      - VPN_SERVICE_PROVIDER=surfshark
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=4F2VxogM0d02Gc+/gQP5LxAQByCIBhBzOavUvUnr7lU= 
      - WIREGUARD_ADDRESSES="10.14.0.2/16"
    cap_add: 
      - NET_ADMIN
    image: qmcgaw/gluetun
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
